In [1]:
import pandas as pd

In [2]:
data = [1,2,3,4,5,10]

In [3]:
data

[1, 2, 3, 4, 5, 10]

In [4]:
type(data)

list

In [5]:
s = pd.Series(data)

In [6]:
s

0     1
1     2
2     3
3     4
4     5
5    10
dtype: int64

In [15]:
type(s)

pandas.core.series.Series

In [18]:
df = pd.DataFrame(s, columns=['num'])
df

   num
0    1
1    2
2    3
3    4
4    5
5   10