In [1]:
import pandas as pd

In [2]:
data = {
    'name':['Shefaul', 'Rakib', 'Shimul'],
    'age' : [24, 23, 25],
    'city' : ['Nilphamari', 'Dinajpur', 'Chuadanga']
}

In [3]:
data

{'name': ['Shefaul', 'Rakib', 'Shimul'],
 'age': [24, 23, 25],
 'city': ['Nilphamari', 'Dinajpur', 'Chuadanga']}

In [4]:
name_series = data['name']

In [5]:
type(name_series)

list

In [6]:
name_series = pd.Series(data['name'], name = 'Name')

In [7]:
name_series

0    Shefaul
1      Rakib
2     Shimul
Name: Name, dtype: object

In [8]:
df = pd.DataFrame(data)

In [9]:
df

      name  age        city
0  Shefaul   24  Nilphamari
1    Rakib   23    Dinajpur
2   Shimul   25   Chuadanga

In [10]:
age_series = pd.Series(data['age'], name = 'Age')

In [11]:
age_series

0    24
1    23
2    25
Name: Age, dtype: int64